#!/bin/bash

URL="http://demoalb-144356215.us-east-1.elb.amazonaws.com/"

for i in {1..10}
do
  #curl -s -w "%{http_code}\n" "$URL"
  curl $URL
  sleep 1  # optional: wait 1 second between requests
done

